# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "= 20190514.0.0"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

  # Work around disconnected virtual network cable.
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qqy update

    # Work around https://github.com/chef/bento/issues/661
    # apt-get -qqy upgrade
    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

    apt-get -qqy install make zip unzip postgresql

    apt-get -qqy install python3 python-pip
    pip3 install --upgrade pip
    pip3 install flask packaging oauth2client redis passlib flask-httpauth
    pip3 install sqlalchemy flask-sqlalchemy psycopg2-binary bleach requests

    apt-get -qqy install python python-pip
    pip2 install --upgrade pip
    pip2 install flask packaging oauth2client redis passlib flask-httpauth
    pip2 install sqlalchemy flask-sqlalchemy psycopg2-binary bleach requests

    su postgres -c 'createuser -dRS vagrant > /vagrant/boot/log/provisioning_createuser.txt 2>&1'
    su vagrant -c 'createdb  >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    su vagrant -c 'createdb news >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    su vagrant -c 'createdb forum >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    su vagrant -c 'createdb restaurant >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    su vagrant -c 'createdb catalog  >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    su vagrant -c 'psql -l >> /vagrant/boot/log/provisioning_createdb.txt 2>&1'
    
    su vagrant -c 'pg_dump catalog > /vagrant/boot/back-up/catalog.sql 2> /vagrant/boot/log/provisioning_pg_dump.txt'
    su vagrant -c 'pg_dump -Ft catalog > /vagrant/boot/back-up/catalog.tar 2> /vagrant/boot/log/provisioning_pg_dump.txt'
    su vagrant -c 'pg_restore -Ft /vagrant/boot/back-up/catalog.tar > /vagrant/boot/log/provisioning_pg_restore.txt 2>&1'

    vagrantTip="[35m[1mThe shared directory is located at /vagrant\\nTo access your shared files: cd /vagrant[m"
    echo -e $vagrantTip > /etc/motd

    wget http://download.redis.io/redis-stable.tar.gz
    tar xvzf redis-stable.tar.gz
    cd redis-stable
    make
    make install

    echo "Done installing your virtual machine!"
  SHELL
end
